deploy:
  overwrite: true
  provider: releases

  api_key:
    secure: NR/ucemwbYbLkqlEt9885kKZuzI/SwNLwoWpLByoI0dS9LgmbNJ0t9kI2UwTV20epotppyNms+CUNfTAS9PPqIjVjKzGn3kyJFwvY11f9/2F6Tv5k+GMFchqbCEtxM/tntSuC0RPrf3tfdXhhAF8h3V4VvrKk8FHXvhaeghMFSQ=

  skip_cleanup: true

  file_glob: true
    file: "libs/global/*"

  on:
    tags: true
    all_branches: true


